-- ============================================================================
-- CampusFind :: 005_notifications_audit.sql
-- Cross-cutting entities: notifications and the audit trail.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- notifications
-- ----------------------------------------------------------------------------
CREATE TABLE notifications (
    notification_id     SERIAL PRIMARY KEY,
    user_id             INTEGER      NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title               VARCHAR(140) NOT NULL,
    body                VARCHAR(400) NOT NULL,
    notification_type   VARCHAR(24)  NOT NULL,
    related_entity_type VARCHAR(20),
    related_entity_id   INTEGER,
    is_read             BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_notif_type CHECK (notification_type IN (
        'MATCH_FOUND', 'CLAIM_SUBMITTED', 'CLAIM_APPROVED',
        'CLAIM_REJECTED', 'ITEM_RETURNED', 'SYSTEM'
    )),
    CONSTRAINT chk_notif_entity CHECK (
        related_entity_type IS NULL OR
        related_entity_type IN ('LOST_ITEM', 'FOUND_ITEM', 'MATCH', 'CLAIM', 'RETURN')
    )
);

COMMENT ON TABLE notifications IS 'In-app messages generated by workflow events.';

-- ----------------------------------------------------------------------------
-- audit_logs
--
-- Append-only history.  actor_id is nullable and ON DELETE SET NULL so that the
-- history survives even if a user account is later removed -- the event still
-- happened.  `details` is JSONB so different actions can carry different
-- context without adding one column per action type.
--
-- Deliberately NOT stored here: passwords, tokens, phone numbers, addresses.
-- ----------------------------------------------------------------------------
CREATE TABLE audit_logs (
    audit_id    BIGSERIAL PRIMARY KEY,
    actor_id    INTEGER     REFERENCES users(user_id) ON DELETE SET NULL,
    action      VARCHAR(30) NOT NULL,
    entity_type VARCHAR(20) NOT NULL,
    entity_id   INTEGER     NOT NULL,
    details     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_audit_action CHECK (action IN (
        'USER_REGISTERED',
        'LOST_ITEM_CREATED',   'LOST_ITEM_UPDATED',
        'FOUND_ITEM_CREATED',  'FOUND_ITEM_UPDATED',
        'QR_GENERATED',        'QR_VERIFIED',
        'MATCH_CREATED',       'MATCH_DISMISSED',
        'CLAIM_SUBMITTED',     'CLAIM_APPROVED', 'CLAIM_REJECTED', 'CLAIM_CANCELLED',
        'ITEM_RETURNED',
        'CATEGORY_UPDATED',    'LOCATION_UPDATED', 'USER_UPDATED'
    )),
    CONSTRAINT chk_audit_entity CHECK (entity_type IN (
        'USER', 'LOST_ITEM', 'FOUND_ITEM', 'MATCH', 'CLAIM',
        'QR_TAG', 'RETURN', 'CATEGORY', 'LOCATION'
    ))
);

COMMENT ON TABLE audit_logs IS 'Append-only trail of every significant action in the system.';
